import type { Metadata } from "next";
import { Alegreya_Sans } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "@/lib/apollo/wrapper";
import { Navbar } from "@/components/Navbar";

const alegreyaSans = Alegreya_Sans({
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body style={{ ...alegreyaSans.style }}>
          <ApolloWrapper>
            <div>
              <Navbar />
              {children}
            </div>
          </ApolloWrapper>
        </body>
      </html>
    </>
  );
}
