import type { Metadata } from "next";
import { Alegreya_Sans } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "@/lib/apollo/wrapper";
import { Navbar } from "@/components/Navbar";

const geistSans = Alegreya_Sans({
  variable: "--font-alegreya-sans",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}`}>
        <ApolloWrapper>
          <div>
            <Navbar />
            {children}
          </div>
        </ApolloWrapper>
      </body>
    </html>
  );
}
